apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devopssemfirula-monitor
spec:
  selector:
    matchLabels:
      app: devopssemfirula
  endpoints:
    - port: http
      interval: 15s
